tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary": "#ffffff",
                "primary": "#000000",
                "on-primary-fixed": "#131b2e",
                "surface-bright": "#f7f9fb",
                "inverse-on-surface": "#eff1f3",
                "tertiary-fixed": "#fcdeb5",
                "on-secondary-fixed-variant": "#004395",
                "on-error-container": "#93000a",
                "on-tertiary-fixed": "#271901",
                "outline": "#76777d",
                "surface-dim": "#d8dadc",
                "error-container": "#ffdad6",
                "primary-fixed-dim": "#bec6e0",
                "on-secondary-fixed": "#001a42",
                "outline-variant": "#c6c6cd",
                "inverse-surface": "#2d3133",
                "on-tertiary-fixed-variant": "#574425",
                "tertiary-fixed-dim": "#dec29a",
                "surface-container-low": "#f2f4f6",
                "on-primary-fixed-variant": "#3f465c",
                "surface-container-lowest": "#ffffff",
                "surface": "#f7f9fb",
                "secondary-container": "#2170e4",
                "tertiary-container": "#271901",
                "surface-tint": "#565e74",
                "secondary-fixed-dim": "#adc6ff",
                "primary-fixed": "#dae2fd",
                "on-background": "#191c1e",
                "tertiary": "#000000",
                "on-error": "#ffffff",
                "on-secondary": "#ffffff",
                "on-primary-container": "#7c839b",
                "on-secondary-container": "#fefcff",
                "secondary-fixed": "#d8e2ff",
                "on-surface": "#191c1e",
                "inverse-primary": "#bec6e0",
                "on-surface-variant": "#45464d",
                "surface-variant": "#e0e3e5",
                "error": "#ba1a1a",
                "surface-container": "#eceef0",
                "primary-container": "#131b2e",
                "on-tertiary": "#ffffff",
                "surface-container-highest": "#e0e3e5",
                "background": "#f7f9fb",
                "secondary": "#0058be",
                "on-tertiary-container": "#98805d",
                "surface-container-high": "#e6e8ea"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-sm": "4px",
                "gutter": "16px",
                "stack-md": "12px",
                "container-margin-mobile": "16px",
                "stack-lg": "24px",
                "container-margin-desktop": "32px",
                "base": "8px"
            },
            "fontFamily": {
                "body-sm": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "display-metric": ["Inter"],
                "headline-md": ["Inter"],
                "headline-lg": ["Inter"],
                "label-caps": ["Inter"],
                "body-lg": ["Inter"]
            },
            "fontSize": {
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "display-metric": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
        },
    },
}
